### ISSUE TITLE
Image with transparent background, generates the wrong marker.

### ISSUE THREAD

**Issue by devsalula** [pablodiegoss/pymarker#11]
**Describe the bug**
When trying to generate a marker image from png with transparent background, it's generating a marker without white background. It fills the background image with black color. 

**Screenshots**
The image I want to generate a marker 
![sleep](https://user-images.githubusercontent.com/35435199/100924218-13c4e200-34bf-11eb-9250-c721b4b0bf54.png)

Genareted Marker
![sleep_marker](https://user-images.githubusercontent.com/35435199/100924358-45d64400-34bf-11eb-9854-8b55966425a0.png)

Expected Marker
![marker](https://user-images.githubusercontent.com/35435199/100925125-563aee80-34c0-11eb-891d-132d602a2186.png)

**Additional Information**
I tried to change the border size to different values, but I kept finding the bug.

Script i used
```
from pymarker.core import generate_patt, generate_marker

def main():
    filename = "top/sleep.png"
    border_size = 10 #size in percentage

    generate_marker(filename, border_size)


if __name__ == "__main__":
    main()
```

**Comment by pablodiegoss** [comment]
Great work guys!! Thanks a lot for the contribution :D
