### ISSUE TITLE
NameError: name 'oen_image' is not defined. Did you mean: 'new_image'?

### ISSUE THREAD

**Issue by marques576** [pablodiegoss/pymarker#14]
After running "pymarker hiro.jpg" I get that error. Is it a typo? Shouldn't it be open_image ?

**Comment by rodrigocam** [comment]
Apparently, this issue has been solved by this commit https://github.com/pablodiegoss/pymarker/commit/a9907d595e9bde2dbcb9615c64bc2c382af29e4b The pipeline didn't pass so I think this may be the reason the last version has this error.

**Comment by rodrigocam** [comment]
Just released a version 0.3.2 that has this problem solved!
