### ISSUE TITLE
Create flag '-o' for output file folder/

### ISSUE THREAD

**Issue by pablodiegoss** [pablodiegoss/pymarker#3]
Using the lib Click, receive the -o flag with an output folder, so that users would be able to use pymarkers as:

`pymarker /tests/input/hiro.jpg -o /tests/output/`
or
`pymarker /tests/input/hiro.jpg -o /tests/output/mypatt.patt`

using pymarker without any output flag should result in the patt being generated at the same path of the input file
`pymarker /tests/input/hiro.jpg` -> /tests/input/hiro.patt is created.

**Comment by hugonxc** [comment]
I'm working on it!
